spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/h99_ecommerce?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qlalf1

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  redis:
    host: localhost
    port: 6379